### ISSUE TITLE
Zastaralý JDBC driver

### ISSUE THREAD

**Issue by Du-St** [fordfrog/ruian2pgsql#30]
Prosím o změnu výchozího JDBC ovladače na novější verzi 9.4. Tato verze obsahuje možnost volby cílového schematu importu.

Dependency by nově mohlo vypadat takto:

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>9.4-1201-jdbc41</version>
        </dependency>

**Comment by fordfrog** [comment]
upraveno v next_release (commit cd8bba33afcd522588286c6da519935e6bb8492b)
